apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-frontend-deployment
  labels:
    app: e-commerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-frontend
  template:
    metadata:
      labels:
        app: e-commerce-frontend
    spec:
      containers:
      - name: nodeserver
        image: praveenthiru/e-commerce-frontend:latest
        ports:
        - containerPort: 3000
