apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-frontend-deployment
  labels:
    app: e-commerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-frontend
  template:
    metadata:
      labels:
        app: e-commerce-frontend
    spec:
      containers:
      - name: nodeserver
        image: praveenthiru/e-commerce-frontend:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: e-commerce-frontend-service
spec:
  selector:
    app: e-commerce-frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
