apiVersion: v1
kind: Service
metadata:
  name: e-commerce-frontend-service
spec:
  selector:
    app: e-commerce-frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
